version: "3.8"

services:
  # BTCPay Server
  btcpayserver:
    image: btcpayserver/btcpayserver:1.13.1
    container_name: btcpay_server
    restart: unless-stopped
    ports:
      - "23000:49392"
    environment:
      # BTCPay Server Configuration
      - BTCPAY_HOST=localhost:23000
      - BTCPAY_BIND=0.0.0.0:49392
      - BTCPAY_CHAINS=btc
      - BTCPAY_BTCEXPLORERURL=http://nbxplorer:32838
      - BTCPAY_BTCLIGHTNING=type=lnd-rest;server=https://lnd:8080;macaroonfilepath=/etc/lnd_bitcoin/admin.macaroon;certfilepath=/etc/lnd_bitcoin/tls.cert
      - BTCPAY_POSTGRES=User ID=postgres;Host=postgres;Port=5432;Database=btcpayserver;Password=btcpayserver123
      - BTCPAY_DEBUGLOG=btcpayserver.log
      - BTCPAY_LOGS=debug
      - BTCPAY_ENABLE_SSH=false
      - BTCPAY_SOCKSENDPOINT=tor:9050
    volumes:
      - btcpay_datadir:/datadir
      - lnd_bitcoin_datadir:/etc/lnd_bitcoin
    depends_on:
      - nbxplorer
      - postgres
      - lnd
    networks:
      - btcpay

  # NBXplorer (Bitcoin blockchain explorer)
  nbxplorer:
    image: nicolasdorier/nbxplorer:2.4.3
    container_name: nbxplorer
    restart: unless-stopped
    ports:
      - "32838:32838"
    environment:
      - NBXPLORER_CHAINS=btc
      - NBXPLORER_BTCRPCURL=http://bitcoind:43782
      - NBXPLORER_BTCRPCUSER=bitcoinrpc
      - NBXPLORER_BTCRPCPASSWORD=bitcoinrpc123
      - NBXPLORER_BTCNODEENDPOINT=bitcoind:39388
      - NBXPLORER_BIND=0.0.0.0:32838
      - NBXPLORER_TRIMEVENTS=10000
      - NBXPLORER_SIGNALFILESDIR=/datadir
    volumes:
      - nbxplorer_datadir:/datadir
    depends_on:
      - bitcoind
    networks:
      - btcpay

  # Bitcoin Core (regtest mode for local development)
  bitcoind:
    image: btcpayserver/bitcoin:26.0
    container_name: bitcoind
    restart: unless-stopped
    ports:
      - "43782:43782"  # RPC
      - "39388:39388"  # P2P
    environment:
      - BITCOIN_NETWORK=regtest
      - BITCOIN_WALLETDIR=/data/wallets
      - BITCOIN_EXTRA_ARGS=-rpcbind=0.0.0.0:43782 -rpcallowip=0.0.0.0/0 -rpcuser=bitcoinrpc -rpcpassword=bitcoinrpc123 -zmqpubrawblock=tcp://0.0.0.0:28332 -zmqpubrawtx=tcp://0.0.0.0:28333 -deprecatedrpc=signrawtransaction
    volumes:
      - bitcoin_datadir:/data
    command: >
      bitcoind -datadir=/data -printtoconsole -server=1 -regtest=1
      -rpcbind=0.0.0.0:43782 -rpcallowip=0.0.0.0/0
      -rpcuser=bitcoinrpc -rpcpassword=bitcoinrpc123
      -zmqpubrawblock=tcp://0.0.0.0:28332 -zmqpubrawtx=tcp://0.0.0.0:28333
      -txindex=1 -deprecatedrpc=signrawtransaction
    networks:
      - btcpay

  # LND Lightning Network Daemon
  lnd:
    image: btcpayserver/lnd:v0.17.0-beta
    container_name: lnd
    restart: unless-stopped
    ports:
      - "8080:8080"   # REST API
      - "10009:10009" # gRPC
    environment:
      - LND_CHAIN=bitcoin
      - LND_ENVIRONMENT=regtest
      - LND_EXTRA_ARGS=--restlisten=0.0.0.0:8080 --rpclisten=0.0.0.0:10009 --bitcoin.active --bitcoin.regtest --bitcoin.node=bitcoind --bitcoind.rpchost=bitcoind:43782 --bitcoind.rpcuser=bitcoinrpc --bitcoind.rpcpass=bitcoinrpc123 --bitcoind.zmqpubrawblock=tcp://bitcoind:28332 --bitcoind.zmqpubrawtx=tcp://bitcoind:28333 --tlsextradomain=lnd
    volumes:
      - lnd_bitcoin_datadir:/data
      - lnd_bitcoin_datadir:/root/.lnd
    depends_on:
      - bitcoind
    networks:
      - btcpay

  # PostgreSQL Database
  postgres:
    image: postgres:15
    container_name: btcpay_postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=btcpayserver123
      - POSTGRES_DB=btcpayserver
    volumes:
      - postgres_datadir:/var/lib/postgresql/data
    networks:
      - btcpay

  # Tor (optional, for privacy)
  tor:
    image: btcpayserver/tor:0.4.7.13
    container_name: btcpay_tor
    restart: unless-stopped
    environment:
      - TOR_EXTRA_ARGS=
    volumes:
      - tor_datadir:/home/tor/.tor
    networks:
      - btcpay

volumes:
  bitcoin_datadir:
  lnd_bitcoin_datadir:
  btcpay_datadir:
  nbxplorer_datadir:
  postgres_datadir:
  tor_datadir:

networks:
  btcpay:
    driver: bridge